services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Enables live code changes
    env_file:
      - app/.env  # Path to your .env file
    depends_on:
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # --reload for live changes

  redis:
    image: redis
    ports:
      - "6379:6379"
